import type { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Fresh Palm Oil',
    slug: 'fresh-palm-oil',
    description:
      'Pure, natural red palm oil sourced directly from trusted farms. Rich in antioxidants and vitamins. Perfect for Nigerian soups and stews.',
    category: 'Oils',
    packagingSize: '5 litres, 10 litres, 25 litres',
    inStock: true,
    imageUrl: '/products/fresh-palm-oil.jpg',
    featured: true,
  },
  {
    id: 2,
    name: 'Egusi (Melon Seeds)',
    slug: 'egusi-melon-seeds',
    description:
      'Premium quality ground egusi (melon seeds) for authentic Nigerian egusi soup. Carefully processed and packaged for maximum freshness.',
    category: 'Soup Ingredients',
    packagingSize: '500g, 1kg, 5kg',
    inStock: true,
    imageUrl: '/products/egusi-melon-seeds.jpg',
    featured: true,
  },
  {
    id: 3,
    name: 'Ogbono (Wild Mango Seeds)',
    slug: 'ogbono-wild-mango-seeds',
    description:
      'High-quality dried and ground ogbono seeds for delicious ogbono soup. Naturally thick and flavourful.',
    category: 'Soup Ingredients',
    packagingSize: '250g, 500g, 1kg',
    inStock: true,
    imageUrl: '/products/ogbono-wild-mango-seeds.jpg',
    featured: true,
  },
  {
    id: 4,
    name: 'White Garri',
    slug: 'white-garri',
    description:
      'Freshly processed white garri made from quality cassava. Great for eba, soaking, and as a snack. Fine and coarse options available.',
    category: 'Grains & Cassava',
    packagingSize: '1kg, 5kg, 10kg, 25kg',
    inStock: true,
    imageUrl: '/products/white-garri.jpg',
    featured: false,
  },
  {
    id: 5,
    name: 'Yellow Garri',
    slug: 'yellow-garri',
    description:
      'Golden yellow garri enriched with palm oil for a richer flavour. A favourite across Nigeria and in the diaspora.',
    category: 'Grains & Cassava',
    packagingSize: '1kg, 5kg, 10kg, 25kg',
    inStock: true,
    imageUrl: '/products/yellow-garri.jpg',
    featured: false,
  },
  {
    id: 6,
    name: 'Ijabu Garri',
    slug: 'ijabu-garri',
    description:
      'Premium coarse-grain garri variety from the Ijabu tradition. Extra crunchy, ideal for soaking with cold water and groundnuts.',
    category: 'Grains & Cassava',
    packagingSize: '1kg, 5kg, 10kg',
    inStock: true,
    imageUrl: '/products/ijabu-garri.jpg',
    featured: true,
  },
  {
    id: 7,
    name: 'Stockfish',
    slug: 'stockfish',
    description:
      'Imported dried stockfish (dried cod) for authentic Nigerian soups. Rich in protein, naturally preserved without additives.',
    category: 'Dried Fish & Seafood',
    packagingSize: 'Per piece, 1kg pack, 5kg bulk',
    inStock: true,
    imageUrl: '/products/stockfish.jpg',
    featured: true,
  },
  {
    id: 8,
    name: 'Dryfish',
    slug: 'dryfish',
    description:
      'Assorted high-quality dried fish for soups and stews. Naturally smoked and sun-dried for maximum flavour and preservation.',
    category: 'Dried Fish & Seafood',
    packagingSize: '500g, 1kg, 5kg',
    inStock: true,
    imageUrl: '/products/dryfish.jpg',
    featured: false,
  },
  {
    id: 9,
    name: 'Crayfish',
    slug: 'crayfish',
    description:
      'Ground dried crayfish for adding deep umami flavour to all Nigerian soups and stews. Pure, no additives or preservatives.',
    category: 'Seafood Seasonings',
    packagingSize: '100g, 250g, 500g, 1kg',
    inStock: true,
    imageUrl: '/products/crayfish.jpg',
    featured: false,
  },
  {
    id: 10,
    name: 'Tin Tomatoes',
    slug: 'tin-tomatoes',
    description:
      'Premium quality canned tomatoes, concentrated and ready for your stews, jollof rice, and Nigerian sauces.',
    category: 'Canned Goods',
    packagingSize: '400g tin, 6-pack, 12-pack',
    inStock: true,
    imageUrl: '/products/tin-tomatoes.jpg',
    featured: false,
  },
  {
    id: 11,
    name: 'White Beans',
    slug: 'white-beans',
    description:
      'Clean, hand-sorted white black-eyed beans. The base for moi moi, akara, and beans porridge. Cooks soft without losing shape.',
    category: 'Beans & Legumes',
    packagingSize: '1kg, 5kg, 10kg, 25kg',
    inStock: true,
    imageUrl: '/products/white-beans.jpg',
    featured: true,
  },
  {
    id: 12,
    name: 'Brown Beans (Oloyin)',
    slug: 'brown-beans',
    description:
      'Sweet honey beans, naturally rich and slightly sweet. A favourite for porridge and beans with plantain. Carefully cleaned and stone-free.',
    category: 'Beans & Legumes',
    packagingSize: '1kg, 5kg, 10kg, 25kg',
    inStock: true,
    imageUrl: '/products/brown-beans.jpg',
    featured: true,
  },
  {
    id: 13,
    name: 'Local Rice',
    slug: 'local-rice',
    description:
      'Nigerian parboiled long-grain rice. Full-bodied and filling, perfect for jollof, white rice, and party cooking. Available by the bag.',
    category: 'Grains & Cassava',
    packagingSize: '5kg, 10kg, 25kg, 50kg',
    inStock: true,
    imageUrl: '/products/local-rice.jpg',
    featured: false,
  },
]
